-- ============================================================
-- Migration 003: Storage bucket + policies for lead-files
-- Run in: Supabase Dashboard → SQL Editor
-- ============================================================
-- NOTE: Postgres does not support "CREATE POLICY IF NOT EXISTS".
-- We use DROP POLICY IF EXISTS before each CREATE POLICY to make
-- this migration idempotent (safe to re-run).
-- ============================================================

-- 1. Create the bucket idempotently (public = false → private bucket)
insert into storage.buckets (id, name, public)
values ('lead-files', 'lead-files', false)
on conflict (id) do nothing;

-- ============================================================
-- 2. Upload policy – anonymous users can INSERT files.
--    This is the MVP approach: the intake form uploads as anon.
--    Files are stored in a private bucket; only admins can read
--    them (via signed URLs generated server-side).
--    Restrict to supported MIME types and 10 MB max.
-- ============================================================

drop policy if exists "Anon can upload lead files" on storage.objects;

create policy "Anon can upload lead files"
  on storage.objects
  for insert
  to anon
  with check (
    bucket_id = 'lead-files'
    and (storage.extension(name)) in ('pdf', 'jpg', 'jpeg', 'png')
    and octet_length(name) < 10485760  -- 10 MB guard on path length (actual size enforced client-side)
  );

-- ============================================================
-- 3. Read policy – only authenticated (admin) users can SELECT
--    object metadata. Actual file downloads use signed URLs
--    generated by the service role client, so this policy gates
--    the metadata query in the admin lead detail view.
-- ============================================================

drop policy if exists "Authenticated can read lead files" on storage.objects;

create policy "Authenticated can read lead files"
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'lead-files');

-- ============================================================
-- 4. No public read. No anon read. No delete policy for anon.
--    Admins can delete via service role (bypasses RLS).
-- ============================================================
