-- ============================================================
-- Migration 005: AI Email Assistant tables
-- ============================================================

-- ============================================================
-- TABLE: case_ai_rules
-- Configurable rules per case type for required/optional fields.
-- ============================================================
create table if not exists case_ai_rules (
  id              uuid primary key default gen_random_uuid(),
  case_type       text not null unique,
  required_fields jsonb not null default '[]',
  optional_fields jsonb not null default '[]',
  risk_rules      jsonb not null default '[]',
  created_at      timestamptz not null default now()
);

-- ============================================================
-- TABLE: case_ai_state
-- Running AI state per lead (lead = case in this system).
-- ============================================================
create table if not exists case_ai_state (
  id                       uuid primary key default gen_random_uuid(),
  lead_id                  uuid unique not null references leads(id) on delete cascade,
  case_type                text not null default 'general',
  summary                  text not null default '',
  missing_fields           jsonb not null default '[]',
  known_facts              jsonb not null default '{}',
  last_analyzed_message_id uuid null,
  last_analyzed_at         timestamptz null,
  confidence_score         numeric not null default 0,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- ============================================================
-- TABLE: case_ai_actions
-- Audit log of every AI call: input, output, model, tokens.
-- ============================================================
create table if not exists case_ai_actions (
  id                uuid primary key default gen_random_uuid(),
  lead_id           uuid not null references leads(id) on delete cascade,
  trigger           text not null,
  input_snapshot    jsonb not null,
  output            jsonb not null,
  status            text not null default 'success' check (status in ('success', 'failed')),
  model             text,
  tokens            jsonb,
  error_message     text,
  created_by_admin_id uuid null,
  created_at        timestamptz not null default now()
);

-- ============================================================
-- TABLE: case_ai_drafts
-- Suggested emails generated by AI for admin approval.
-- ============================================================
create table if not exists case_ai_drafts (
  id                uuid primary key default gen_random_uuid(),
  lead_id           uuid not null references leads(id) on delete cascade,
  conversation_id   uuid not null references email_conversations(id) on delete cascade,
  suggested_subject text not null,
  suggested_text    text not null,
  suggested_html    text,
  questions         jsonb not null default '[]',
  status            text not null default 'proposed'
                      check (status in ('proposed', 'approved', 'sent', 'discarded')),
  source_action_id  uuid null references case_ai_actions(id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- ============================================================
-- INDEXES
-- ============================================================
create index if not exists case_ai_actions_lead_created_idx
  on case_ai_actions(lead_id, created_at desc);

create index if not exists case_ai_drafts_lead_created_idx
  on case_ai_drafts(lead_id, created_at desc);

create index if not exists case_ai_drafts_conversation_idx
  on case_ai_drafts(conversation_id, created_at desc);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table case_ai_rules enable row level security;
alter table case_ai_state enable row level security;
alter table case_ai_actions enable row level security;
alter table case_ai_drafts enable row level security;

-- case_ai_rules: admins can read (config is read-only from UI)
create policy "Admin can read case_ai_rules"
  on case_ai_rules for select to authenticated using (true);

create policy "Admin can manage case_ai_rules"
  on case_ai_rules for all to authenticated using (true) with check (true);

-- case_ai_state: admins can read and update
create policy "Admin can read case_ai_state"
  on case_ai_state for select to authenticated using (true);

create policy "Admin can insert case_ai_state"
  on case_ai_state for insert to authenticated with check (true);

create policy "Admin can update case_ai_state"
  on case_ai_state for update to authenticated using (true) with check (true);

-- case_ai_actions: admins can read (audit log)
create policy "Admin can read case_ai_actions"
  on case_ai_actions for select to authenticated using (true);

create policy "Admin can insert case_ai_actions"
  on case_ai_actions for insert to authenticated with check (true);

-- case_ai_drafts: admins can read and manage
create policy "Admin can read case_ai_drafts"
  on case_ai_drafts for select to authenticated using (true);

create policy "Admin can insert case_ai_drafts"
  on case_ai_drafts for insert to authenticated with check (true);

create policy "Admin can update case_ai_drafts"
  on case_ai_drafts for update to authenticated using (true) with check (true);

-- Enable Realtime for drafts (for live updates in UI):
--   alter publication supabase_realtime add table case_ai_drafts;
--   alter publication supabase_realtime add table case_ai_state;

-- ============================================================
-- SEED: Initial case_ai_rules for common case types
-- ============================================================
insert into case_ai_rules (case_type, required_fields, optional_fields, risk_rules) values

('פיטורים', '[
  {"key":"employment_start_date","label":"תאריך תחילת עבודה","question":"מה תאריך תחילת העבודה?","priority":1},
  {"key":"employment_end_date","label":"תאריך סיום עבודה","question":"מה תאריך סיום העבודה?","priority":1},
  {"key":"last_salary","label":"שכר אחרון","question":"מה היה השכר האחרון (ברוטו)?","priority":1},
  {"key":"termination_reason","label":"סיבת פיטורים","question":"מה הייתה סיבת הפיטורים?","priority":1},
  {"key":"prior_notice","label":"הודעה מוקדמת","question":"האם קיבלת הודעה מוקדמת? כמה זמן?","priority":2},
  {"key":"severance_received","label":"פיצויי פיטורים","question":"האם קיבלת פיצויי פיטורים?","priority":1},
  {"key":"pension_status","label":"מצב פנסיה","question":"האם הופרשו כספי פנסיה לכל תקופת העבודה?","priority":2},
  {"key":"vacation_balance","label":"ימי חופשה","question":"האם נותרו ימי חופשה שלא נוצלו?","priority":2},
  {"key":"employer_name","label":"שם המעסיק","question":"מה שם המעסיק?","priority":1},
  {"key":"hearing_held","label":"שימוע","question":"האם נערך לך שימוע לפני הפיטורים?","priority":1}
]', '[]', '[
  {"condition":"no_hearing","label":"לא נערך שימוע","severity":"high"},
  {"condition":"no_severance","label":"לא שולמו פיצויים","severity":"high"},
  {"condition":"no_prior_notice","label":"לא ניתנה הודעה מוקדמת","severity":"medium"}
]'),

('התפטרות', '[
  {"key":"employment_start_date","label":"תאריך תחילת עבודה","question":"מה תאריך תחילת העבודה?","priority":1},
  {"key":"employment_end_date","label":"תאריך סיום עבודה","question":"מה תאריך סיום העבודה?","priority":1},
  {"key":"last_salary","label":"שכר אחרון","question":"מה היה השכר האחרון (ברוטו)?","priority":1},
  {"key":"resignation_reason","label":"סיבת התפטרות","question":"מה הייתה הסיבה להתפטרות?","priority":1},
  {"key":"prior_notice_given","label":"הודעה מוקדמת ניתנה","question":"האם נתת הודעה מוקדמת למעסיק?","priority":2},
  {"key":"pension_status","label":"מצב פנסיה","question":"האם הופרשו כספי פנסיה לכל תקופת העבודה?","priority":2},
  {"key":"vacation_balance","label":"ימי חופשה","question":"האם נותרו ימי חופשה שלא נוצלו?","priority":2},
  {"key":"employer_name","label":"שם המעסיק","question":"מה שם המעסיק?","priority":1},
  {"key":"conditions_deteriorated","label":"הרעת תנאים","question":"האם חלה הרעה בתנאי העבודה לפני ההתפטרות?","priority":2}
]', '[]', '[
  {"condition":"conditions_deteriorated","label":"הרעת תנאים","severity":"high"},
  {"condition":"no_pension","label":"לא הופרשה פנסיה","severity":"medium"}
]'),

('אי_תשלום_שכר', '[
  {"key":"employment_start_date","label":"תאריך תחילת עבודה","question":"מה תאריך תחילת העבודה?","priority":1},
  {"key":"employer_name","label":"שם המעסיק","question":"מה שם המעסיק?","priority":1},
  {"key":"agreed_salary","label":"שכר מוסכם","question":"מה השכר המוסכם (ברוטו)?","priority":1},
  {"key":"unpaid_months","label":"חודשים לא שולמו","question":"אילו חודשים לא שולמו?","priority":1},
  {"key":"partial_or_full","label":"חלקי או מלא","question":"האם השכר לא שולם כלל או שולם באופן חלקי?","priority":1},
  {"key":"written_contract","label":"חוזה כתוב","question":"האם יש חוזה עבודה כתוב?","priority":2},
  {"key":"demand_letter_sent","label":"מכתב דרישה","question":"האם נשלח מכתב דרישה למעסיק?","priority":2},
  {"key":"still_employed","label":"עדיין מועסק","question":"האם אתה עדיין עובד אצל אותו מעסיק?","priority":1}
]', '[]', '[
  {"condition":"multiple_months","label":"כמה חודשים ללא תשלום","severity":"high"},
  {"condition":"no_contract","label":"אין חוזה כתוב","severity":"medium"}
]'),

('שעות_נוספות', '[
  {"key":"employment_start_date","label":"תאריך תחילת עבודה","question":"מה תאריך תחילת העבודה?","priority":1},
  {"key":"employer_name","label":"שם המעסיק","question":"מה שם המעסיק?","priority":1},
  {"key":"weekly_hours","label":"שעות עבודה שבועיות","question":"כמה שעות אתה עובד בשבוע?","priority":1},
  {"key":"overtime_hours_monthly","label":"שעות נוספות חודשיות","question":"כמה שעות נוספות בערך בחודש?","priority":1},
  {"key":"overtime_paid","label":"תשלום שעות נוספות","question":"האם שעות נוספות משולמות? באופן חלקי?","priority":1},
  {"key":"attendance_records","label":"דיווח נוכחות","question":"האם מתנהל דיווח נוכחות (שעון, אפליקציה)?","priority":2},
  {"key":"base_salary","label":"שכר בסיס","question":"מה שכר הבסיס (ברוטו)?","priority":1},
  {"key":"global_overtime_clause","label":"סעיף שעות גלובליות","question":"האם יש סעיף שעות גלובליות בחוזה?","priority":2},
  {"key":"still_employed","label":"עדיין מועסק","question":"האם אתה עדיין עובד אצל אותו מעסיק?","priority":1}
]', '[]', '[
  {"condition":"no_records","label":"אין דיווח נוכחות","severity":"medium"},
  {"condition":"global_clause","label":"סעיף שעות גלובליות","severity":"low"}
]'),

('general', '[
  {"key":"employment_start_date","label":"תאריך תחילת עבודה","question":"מה תאריך תחילת העבודה?","priority":1},
  {"key":"employer_name","label":"שם המעסיק","question":"מה שם המעסיק?","priority":1},
  {"key":"last_salary","label":"שכר אחרון","question":"מה השכר האחרון (ברוטו)?","priority":1},
  {"key":"employment_end_date","label":"תאריך סיום עבודה","question":"מה תאריך סיום העבודה (אם רלוונטי)?","priority":2},
  {"key":"main_issue","label":"בעיה עיקרית","question":"מה הנושא העיקרי שברצונך לבדוק?","priority":1},
  {"key":"still_employed","label":"עדיין מועסק","question":"האם אתה עדיין עובד אצל אותו מעסיק?","priority":2}
]', '[]', '[]')

on conflict (case_type) do nothing;
